// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTest.Data.Persistence;

#nullable disable

namespace NetTest.Data.Migrations
{
    [DbContext(typeof(NetTestDbContext))]
    [Migration("20260804171314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NetTest.Data.Entities.ProbeExecution", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddressFamily")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CancellationReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupIdSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetricsSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PrimaryLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProbeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProbeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggerKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("PlanId", "CompletedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("ProbeId", "CompletedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "CompletedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("TriggerKind", "CompletedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ProbeExecutions", (string)null);
                });

            modelBuilder.Entity("NetTest.Data.Entities.ProbeRun", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CancellationReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationRevision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanNameSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggerKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "StartedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "StartedAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("TriggerKind", "StartedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ProbeRuns", (string)null);
                });

            modelBuilder.Entity("NetTest.Data.Entities.ProbeExecution", b =>
                {
                    b.HasOne("NetTest.Data.Entities.ProbeRun", "Run")
                        .WithMany("Executions")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("NetTest.Data.Entities.ProbeRun", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
